### ISSUE TITLE
[FE]: Create NavBar

### ISSUE THREAD

**Issue by KevinLatino** [StarShopCr/StarShop-Frontend#27] opened 2024-12-11 23:40 UTC
> [!IMPORTANT]  
Before applying, please read the [Contributors Guide](https://github.com/StarShopCr/contributors-guide). Following the guide increases your chances of being assigned to this task.  

# Create NavBar  

## Description  
Create a navigation bar for the application. The `NavBar` should allow users to easily navigate between different sections of the platform, such as the Dashboard, Products, Setting etc.

## Requirements  

1. **Component Location**:  
   - The `NavBar` component  is inside the `src/components/ui` folder.  
   - You just have to edit the `NavBarComponent.tsx` file.  

2. **Functionality**:  
   - Include links to important sections such as the dashboard, settings (Products doesn't have a route yet).  
   - Ensure accessibility features such as keyboard navigation and screen reader support.

3. **UI Design**:  
   - Align the design with the overall platform branding and color scheme.  
   - Use icons and text for the navigation items, ensuring a clean and user-friendly interface, Follow the provided [Figma design](https://www.figma.com/design/OsBwtlrTh74tPs3S3MZm1N/StarShop-Figma?node-id=0-1&node-type=canvas&t=pVTHQecm3MDfgGXN-0).

# Image
<img width="918" alt="Captura de pantalla 2024-12-08 a las 7 44 18 p  m" src="https://github.com/user-attachments/assets/5693d7c0-84c0-4137-9000-6782dfd54cf4" />

**Comment by mimisavage** [comment] 2024-12-11 23:49
Can I take this issue?

**Comment by robertram** [comment] 2024-12-11 23:58
Hi, I am from de Dojo Coding community and a new contributor to Only Dust. Im a web3 frontend developer and founder of a NFT ticketing platform. 
ETA: 1-2 days.
The way I would approach this is modify the NavBarComponent.tsx file following the Figma design. Add accesibility features like the keyboard navigation and screen reader support.  And test on different devices.

**Comment by mymiracle0118** [comment] 2024-12-12 00:30
May I be assigned to this?

**Comment by ozo-vehe** [comment] 2024-12-12 02:51
Estimated completion time: 1-2 days

To create the NavBar, I will:

1. Review the Figma design for the NavBar.
2. Edit the existing NavBarComponent.tsx file to match the design.
3. Implement links to the dashboard and settings sections.
4. Ensure accessibility features such as keyboard navigation and screen reader support.
5. Align the design with the overall platform branding and color scheme.
6. Test the NavBar for functionality and UI consistency with the Figma design.

**Comment by Yunusabdul38** [comment] 2024-12-12 05:04
Estimated Completion Time (ETA): I estimate completing this issue within 2 days.
Plan:
Understand Design: Review the Figma design and align the NavBar with the platform’s branding and color scheme.

Develop Structure: Edit NavBarComponent.tsx to include navigation links for easy navigation between different sections of the platform

Accessibility: Implement keyboard navigation, ARIA roles, and labels for screen reader compatibility. Ensure the navigation is intuitive for all users.

Styling: Use Tailwind CSS or the project’s styling framework to create a visually appealing and responsive NavBar.

Test: Validate functionality across devices and browsers, including testing navigation and accessibility features.

Submit: Finalize and submit the NavBar implementation for review.

**Comment by pheobeayo** [comment] 2024-12-12 05:38
Can I take care of this issue?

I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun scaffold-stark.

I will follow the figma design in the implementation of this issue.

**Comment by LawalRahman** [comment] 2024-12-12 10:17
I’d like to resolve this.

**Comment by drakkomaximo** [comment] 2024-12-12 12:04
Hi everyone!

I’d be excited to work on creating the NavBar for the application. With over 5 years of experience in frontend development, I’ve built plenty of navigation components and know how important it is to make them intuitive, accessible, and visually aligned with the platform’s style.

Estimated time: 1-2 days

How I’ll approach it:

1. Start by reviewing the provided Figma design to ensure the NavBar matches the branding and style.
2. Edit the NavBarComponent.tsx file located in src/components/ui.
3. Add links to key sections like the Dashboard and Settings, ensuring a clean and functional layout (noting that Products doesn’t have a route yet).
4. Focus on accessibility, implementing keyboard navigation and screen reader support.
5. Use both icons and text for the navigation items to make it user-friendly and visually balanced.

Let me know if you’d like me to start on this!

**Comment by josephchimebuka** [comment] 2024-12-12 13:50
Could I try solving this?

**Comment by robertram** [comment] 2024-12-12 14:00
Hi, I am from de Dojo Coding community and a new contributor to Only Dust. Im a web3 frontend developer and founder of a NFT ticketing platform. 
ETA: 1-2 days.
The way I would approach this is modify the NavBarComponent.tsx file following the Figma design. Add accesibility features like the keyboard navigation and screen reader support. And test on different devices.

**Comment by ozo-vehe** [comment] 2024-12-12 14:03
Estimated completion time: 1-2 days

To create the NavBar, I will:

1. Review the Figma design for the NavBar.
2. Edit the existing NavBarComponent.tsx file to match the design.
3. Implement links to the dashboard and settings sections.
4. Ensure accessibility features such as keyboard navigation and screen reader support.
5. Align the design with the overall platform branding and color scheme.
6. Test the NavBar for functionality and UI consistency with the Figma design.

**Comment by SimplementeCao** [comment] 2024-12-12 14:05
---

### Hey! I'm *SimplementeCao*. 👋

I have contributed before to other projects like:

- `Cairo Book`
- `Starknet Book`
- `Starknet Docs`
- `Starknet Security Challenges Factory`
- `Starkane`

Can I work on this issue?

Check my OnlyDust, I've contributed to many projects: [OnlyDust Profile](https://app.onlydust.com/u/SimplementeCao), 
and my [GitHub](https://github.com/SimplementeCao)

---

### Plan to Solve the Issue:

1. **Analyze the codebase** to understand the current structure and functionality.
2. **Review the problem description** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I face any challenge, I will **ask questions promptly** in the relevant support group or communication channel to move forward efficiently.
5. Once resolved, I will **open a PR** and wait for your feedback.

---

Let me know if I can start working on this! 🚀

---

**Comment by derianrddev** [comment] 2024-12-12 14:07
**Hello StarShop Team,**

I am **Derian Rodríguez**, a member of the **Dojo Coding** community ⛩️💻. I’m thrilled about the opportunity to contribute to your **Stellar**-based project during the **Only Dust Hackathon #11** 🚀.

As a **full-stack** developer, I have experience in:

- **Frontend:** JavaScript/TypeScript, TailwindCSS, React, Next.js, and shadcn/ui.
- **Backend:** Node.js (Express.js, Nest.js).
- **Web3:** Cairo.

### Plan to Address the *Issue*

1. Build the NavBar structure in `NavBarComponent.tsx` with links to the *Dashboard* and *Settings*.
2. Ensure accessibility with keyboard support and ARIA labels.
3. Apply the design based on the Figma scheme, incorporating the logo, icon, and text.
4. Test functionality and design to ensure usability and compatibility.

Here are my profiles for more details:

- [**GitHub**](https://github.com/derianrddev)
- [**OnlyDust**](https://app.onlydust.com/u/derianrddev)

Thank you for considering my application.

**Comment by SYLVIANNORUKA** [comment] 2024-12-12 14:10
Let me try this one!I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, . I would love to contribute to this project.

**Comment by Steph3097** [comment] 2024-12-12 14:11
Hi @KevinLatino! Im Sttef,
I’m part of Dojo Coding and I would love to contribute to this project. I have over 5 years of experience in front-end development and i really like to follow design files and bring them to live.  
Here’s how I’ll approach the task:
-I will check the figma file and start editing the NavBar component based on the design 
-Add the links to the desired sections
-Add accessibility features  to navBar component
-Use the requested icons
-Check that the navbar has the expected behavior and that the design looks good 
I’m looking forward to contributing to this task! Thank you for considering my application.

**Comment by Benjtalkshow** [comment] 2024-12-12 14:12
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by SudiptaPaul-31** [comment] 2024-12-12 14:18
I think I can resolve this issue

My approach:

Will start by seeing the figma file and try to replicate that on the webpage and profile all the necessary css properties and making sure that its responsive and at last making a pr.

ETA: 2day

**Comment by jpool09** [comment] 2024-12-12 14:21
Hi team,
My name is Jean Pool Cruz, and I’m an experienced Developer with over 5 years of experience building web applications using technologies like React, TypeScript, and Tailwind CSS. I’ve worked extensively with component libraries and UI design, ensuring alignment with branding and accessibility standards, and I'm a Dojo Coding Member ⛩️

Plan to Solve the Issue:
1. Understand Requirements:
    * Review the Contributor’s Guide and Figma design to ensure the NavBar aligns perfectly with the platform’s branding and UI guidelines.
    * Verify the existing routing and structure for smooth integration.
2. Develop the NavBar Component:
    * Edit the NavBarComponent.tsx file in src/components/ui.
    * Add navigation links for the Dashboard and Settings, using a combination of icons and text for clarity.
    * Ensure the NavBar is fully responsive and adheres to accessibility standards.
3. Test:
    * Test the NavBar for responsiveness, accessibility, and smooth navigation across routes.
    * Validate against the provided Figma design to ensure pixel-perfect implementation.
4. Document:
    * Add inline comments and update any relevant documentation for future maintainability.

Estimated Time of Completion (ETA): I estimate completing the task within 1 day, with a focus on ensuring quality and accessibility.
Please let me know if there’s any additional information I should consider before starting. I’m eager to contribute to this project and look forward to your response!

**Comment by QuiqueCode** [comment] 2024-12-12 14:22
## 👤 *Personal information*
My name is Dylan Castillo, a developer passionate about technology and computing. I have a focus on frontend development, where I am constantly learning and evolving. I have experience in creating dynamic and functional applications using React. I always seek to develop efficient, scalable solutions focused on user experience.

## 🧢 *OnlyDust Info*

I’ve contributed to a project on the OnlyDust platform. Check out my profile on [OnlyDust](https://app.onlydust.com/u/QuiqueCode) to learn more about my work.

## 🛠 *General Project Requirements*

-   The navigation should include links to essential sections like the dashboard and settings (note: Products route is not yet available).
-   Ensure accessibility by enabling keyboard navigation and supporting screen readers for improved usability.

## 💡 *Proposal*

I will design a future-proof navigation system that will accommodate evolving user needs. This will allow future developers to seamlessly add new navigation items as the application grows and changes.

## 🌟 *Benefits*

-   *Scalability:* The proposed structure will streamline the integration of new navigation items.
- *ETA*: 24 hours

**Comment by Emmykeyz101** [comment] 2024-12-12 14:36
Would love to tackle this!

**Comment by jpool09** [comment] 2024-12-12 14:45
Hi team,
My name is Jean Pool Cruz, and I’m an experienced Developer with over 5 years of experience building web applications using technologies like React, TypeScript, and Tailwind CSS. I’ve worked extensively with component libraries and UI design, ensuring alignment with branding and accessibility standards.

Plan to Solve the Issue:
1. Understand Requirements:
    * Review the Contributor’s Guide and Figma design to ensure the NavBar aligns perfectly with the platform’s branding and UI guidelines.
    * Verify the existing routing and structure for smooth integration.
2. Develop the NavBar Component:
    * Edit the NavBarComponent.tsx file in src/components/ui.
    * Add navigation links for the Dashboard and Settings, using a combination of icons and text for clarity.
    * Ensure the NavBar is fully responsive and adheres to accessibility standards.
3. Test:
    * Test the NavBar for responsiveness, accessibility, and smooth navigation across routes.
    * Validate against the provided Figma design to ensure pixel-perfect implementation.
4. Document:
    * Add inline comments and update any relevant documentation for future maintainability.

Estimated Time of Completion (ETA): I estimate completing the task within 1 day, with a focus on ensuring quality and accessibility.
Please let me know if there’s any additional information I should consider before starting. I’m eager to contribute to this project and look forward to your response!

Best regards, 
Jean Pool Cruz

**Comment by 7-falseparfait** [comment] 2024-12-12 14:49
I am a Front-end and Smart Contract Developer with expertise in Tailwind CSS, Next.js, TypeScript, JavaScript, and SQL. I am eager to contribute to this project and bring value with my skills. Could I be Assigned this.

**Comment by Akshola00** [comment] 2024-12-12 14:49
Hello, I'm Akinshola Akinniyi, a frontend developer with experience in creating responsive and accessible user interfaces. After completing the Cairo Basecamp, I have worked on various projects, focusing on building intuitive navigation systems and ensuring seamless user experience.

I would love to take on the task of creating the NavBar component. With my experience in implementing designs from Figma, I can ensure the navigation bar aligns with the platform's branding, uses appropriate icons and text for the links, and includes accessibility features such as keyboard navigation and screen reader support. Please assign me this task—I’m excited to contribute to the project!

ETA 1 DAY

**Comment by Belloabraham121** [comment] 2024-12-12 14:50
Hey! I'm Iteooluwakisi.
Member of Web3bridge. I have contributed before to other projects like:
• CoinSafe 
• Scaffold-ETH
• BuidlGuidl
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by melnikga** [comment] 2024-12-12 14:50
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by QuiqueCode** [comment] 2024-12-12 14:58
## 👤 *Personal information*
My name is Dylan Castillo, a developer passionate about technology and computing. I have a focus on frontend development, where I am constantly learning and evolving. I have experience in creating dynamic and functional applications using React. I always seek to develop efficient, scalable solutions focused on user experience.

## 🧢 *OnlyDust Info*

I’ve contributed to a project on the OnlyDust platform. Check out my profile on [OnlyDust](https://app.onlydust.com/u/QuiqueCode) to learn more about my work.

## 🛠 *General Project Requirements*

-   The navigation should include links to essential sections like the dashboard and settings (note: Products route is not yet available).
-   Ensure accessibility by enabling keyboard navigation and supporting screen readers for improved usability.

## 💡 *Proposal*

I will design a future-proof navigation system that will accommodate evolving user needs. This will allow future developers to seamlessly add new navigation items as the application grows and changes.

## 🌟 *Benefits*

-   *Scalability:* The proposed structure will streamline the integration of new navigation items.
- *ETA*: 24 hours

**Comment by abdegenius** [comment] 2024-12-12 14:58
Could I take a shot at this?

**Comment by vestor-dev** [comment] 2024-12-12 15:01
i'm a frontend dev and blockchain dev 
May I try my hand at this?
i would love to work on this and get it done

**Comment by 0xdevcollins** [comment] 2024-12-12 15:02
Could I try solving this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by kimcascante** [comment] 2024-12-12 15:03
Hi @KevinLatino I'm Kimberly Cascante, a proud member of Dojo Coding! ⛩️
I have previously worked with TypeScript, to disable a button based on specific criteria. I'm passionate about design and frontend development and excited to contribute to this project.
My plan is to start by reviewing the Component, then proceed to edit it, following the project's structure and figma design. I'll ensure proper validations, test it, and prepare a PR for review. Happy to contribute!

**Comment by Yunusabdul38** [comment] 2024-12-12 15:04
Plan:
Understand Design: Review the Figma design and align the NavBar with the platform’s branding and color scheme.

Develop Structure: Edit NavBarComponent.tsx to include navigation links for easy navigation between different sections of the platform

Accessibility: Implement keyboard navigation, ARIA roles, and labels for screen reader compatibility. Ensure the navigation is intuitive for all users.

Styling: Use Tailwind CSS or the project’s styling framework to create a visually appealing and responsive NavBar.

Test: Validate functionality across devices and browsers, including testing navigation and accessibility features.

Submit: Finalize and submit the NavBar implementation for review.

**Comment by Pvsaint** [comment] 2024-12-12 15:08
I’d love to work on this task please, I'm Victor Peter, a frontend and smart contract developer. I promise to write a pixel perfect code, I'm a first time contributor in this repo

**Comment by chigozzdevv** [comment] 2024-12-12 15:10
Hello sir, please can this be assigned to me?

**Comment by jedstroke** [comment] 2024-12-12 15:11
I'd like to take this issue my ETA will be 1 days

**Comment by 3th-Enjay** [comment] 2024-12-12 15:11
Would love to tackle this!

**Comment by Bran18** [comment] 2024-12-12 15:12
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #12! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• X: https://x.com/branfdez_18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by Jagadeeshftw** [comment] 2024-12-12 15:12
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by FrankiePower** [comment] 2024-12-12 15:13
My name is Super Franky, i am a frontend developer with 3+ years experience and recently graduated from web3bridge africa, the premier and biggest blockhain developer community in africa. i am well equipped to build out the navbar component  and ensure it has accessibility features. This project will take me a day to complete.

**Comment by davedumto** [comment] 2024-12-12 15:13
Hi I am David, I am a frontend web developer that specializes in Typescript, Javascript and tailwindcss. I plan to approach this issue by building the "Navbar" component to be reusable and responsive. ETA 2 days

**Comment by Kachimercy1** [comment] 2024-12-12 15:14
I'd love to give this a go.

**Comment by kayceeDev** [comment] 2024-12-12 15:14
Can I tackle this one?

**Comment by kimcascante** [comment] 2024-12-12 15:14
Hi @KevinLatino I'm Kimberly Cascante, a member of Dojo Coding! ⛩️
I have previously worked with TypeScript, to disable button based on specific criteria. I'm passionate about design and frontend development and excited to contribute to this project.
My plan is to start by reviewing the NavBar component, then proceed to edit it, following the project's structure and figma design. I'll ensure proper validations, test the solution, and prepare a PR for review.
 Happy to contribute!

**Comment by Shalomnze** [comment] 2024-12-12 15:15
I am Nze Shalom, a full stack developer with strong foundation in modern web development frameworks and technologies. My expertise includes: Nuxt.js, Next.js and Tailwind CSS with a bit of knowledge in Cairo. I am Experienced in crafting responsive, visually appealing designs using Tailwind CSS, ensuring consistency and efficiency in the development process. I would love to contribute to this project.

How I plan on tackling this issue
My approach towards this issue after forking the repo and creating the branch I would work on, would be to first export the background image and other assets ( like the logo and icons used so as to maintain consistency with the brand). I would locate the component file in src/components/ui. I would then set the image as the background of the nav bar. I would then import the logo and create the links for the various pages then style it as it looks in the design. ETA is 24hrs

**Comment by Kaminar-i** [comment] 2024-12-12 15:15
Can I hop on this

**Comment by ryzen-xp** [comment] 2024-12-12 15:49
Hi,
 I am a proficient blockchain developer with expertise in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects.
I will create the NavBar component in the src/components/ui/NavBarComponent.tsx, ensuring functionality with links to the Dashboard and Settings, and incorporating accessibility features. I will follow the Figma design and align it with the platform's branding and color scheme.

Please assign this issue to me.

Thank you!

**Comment by ShantelPeters** [comment] 2024-12-12 15:56
I’d like to help with this.

**Comment by MooreTheAnalyst** [comment] 2024-12-12 15:58
This is an issue i would love to work on and i easily can create this. 
can i be assigned this issue?

**Comment by therealemino** [comment] 2024-12-12 16:44
I'd love to give this a go.

**Comment by emmz3230** [comment] 2024-12-12 16:44
I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.

I will make sure to create a responsive navbar for all devices using the Figma design that also make use of the keyboard navigation such as keydown and keyup properties

thanks will love to contribute to this project

**Comment by MPSxDev** [comment] 2024-12-12 18:38
Hi, I'm Manuel, a developer and process engineer. 
I would resolve the issue first by reviewing the Figma design and adjusting to the component-based development guideline to maintain project consistency and scalability. 
Estimated delivery time: 20 hours.

**Comment by KevinLatino** [comment] 2024-12-12 18:43
@MPSxDev Task assigned to you. Let me know if you need further clarification or additional support!😊
Here is our telegram group, please join https://t.me/starshopcr

**Closed** 2024-12-13 17:23 UTC
Labels: good first issue, ODHACK11, Frontend
